// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYeqd6UouJDwPhCyYYZaj94sax0S-RZ-k',
    appId: '1:1010490620718:web:884db96725467cd88198bf',
    messagingSenderId: '1010490620718',
    projectId: 'my-pet-feeder-18354',
    authDomain: 'my-pet-feeder-18354.firebaseapp.com',
    databaseURL: 'https://my-pet-feeder-18354-default-rtdb.firebaseio.com',
    storageBucket: 'my-pet-feeder-18354.firebasestorage.app',
    measurementId: 'G-PNJY827X6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5xsyifM-2f1y8kBwyA9ZV2RszF0dpXU',
    appId: '1:1010490620718:android:fdceec4e056e34ab8198bf',
    messagingSenderId: '1010490620718',
    projectId: 'my-pet-feeder-18354',
    databaseURL: 'https://my-pet-feeder-18354-default-rtdb.firebaseio.com',
    storageBucket: 'my-pet-feeder-18354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqdofYc6T998p6t_ZBS8ryRSX_0tc51I',
    appId: '1:1010490620718:ios:df5c0e33ffd098348198bf',
    messagingSenderId: '1010490620718',
    projectId: 'my-pet-feeder-18354',
    databaseURL: 'https://my-pet-feeder-18354-default-rtdb.firebaseio.com',
    storageBucket: 'my-pet-feeder-18354.firebasestorage.app',
    iosBundleId: 'com.example.pettapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqdofYc6T998p6t_ZBS8ryRSX_0tc51I',
    appId: '1:1010490620718:ios:df5c0e33ffd098348198bf',
    messagingSenderId: '1010490620718',
    projectId: 'my-pet-feeder-18354',
    databaseURL: 'https://my-pet-feeder-18354-default-rtdb.firebaseio.com',
    storageBucket: 'my-pet-feeder-18354.firebasestorage.app',
    iosBundleId: 'com.example.pettapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYeqd6UouJDwPhCyYYZaj94sax0S-RZ-k',
    appId: '1:1010490620718:web:9fce3b04b82ed63c8198bf',
    messagingSenderId: '1010490620718',
    projectId: 'my-pet-feeder-18354',
    authDomain: 'my-pet-feeder-18354.firebaseapp.com',
    databaseURL: 'https://my-pet-feeder-18354-default-rtdb.firebaseio.com',
    storageBucket: 'my-pet-feeder-18354.firebasestorage.app',
    measurementId: 'G-LN1CM5C20K',
  );
}
